### PR TITLE
Adding orgs!

### PR DESCRIPTION
**Pull request by sirjessthebrave**
Are there qualifications as to what org's are included in this list?

### CODE REVIEW

**Comment by alishalisha** [comment]
Hey thanks @sirjessthebrave! ✨ The qualifications are that:

- It's an organization working to improve diversity and inclusion in technology
- It's an organization actively looking for volunteers who can help with teaching, mentoring, or any other programming they may have

I should make this more clear in the README! Let me know if you'd like to revisit some of the orgs you've added here or if this is ok to merge.

**Comment by sirjessthebrave** [comment]
Perfect @alishalisha! I think all these orgs fit those qualifications! Thanks for doing this!

**Comment by jancborchardt** [comment]
So this seems ok to merge, right @alishalisha? :)

**Comment by alishalisha** [comment]
Thank you!

**Pull request merged**
